name: Node js test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  buildtest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v2.5.0
        with:
          node-version: '14.x'
          
      - run: npm ci
      - run: npm run build
      - run: npm test

   publish:
    needs: buildtest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.13 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "deploy-test-awesome" #Must be unique in Heroku
          heroku_email: "laicheehoong@gmail.com"

