name: Node js test

on: 
  push:
    branches: [master]

jobs: 
  buildtest:
    runs-on: ubuntu-latest
    steps:
      -   uses: actions/checkout
      -   uses: actions/setup-node
          with:
              node-version: 13
      - run: npm ci
      - run: npm run build
      - run: npm test


